project:
  type: website
  output-dir: docs

website:
  title: "Pavia 2026"
  reader-mode: false
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: lectures/index.qmd
        text: Lectures
      - href: notebooks/index.qmd  
        text: Workshop
    right:
      - text: About
        href: about.qmd
      - icon: github
        aria-label: github
        href: https://github.com/veroandreo/pavia-2026
  page-footer:
    center:
      - text: "&#169; 2026 Verónica Andreo, <span xmlns:cc=\"http://creativecommons.org/ns#\" xmlns:dct=\"http://purl.org/dc/terms/\">licensed under <a href=\"http://creativecommons.org/licenses/by/4.0/?ref=chooser-v1\" target=\"_blank\" rel=\"license noopener noreferrer\" style=\"display:inline-block;\">CC BY 4.0<img style=\"height:18px!important;margin-left:3px;vertical-align:text-bottom;\" src=\"https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1\"><img style=\"height:18px!important;margin-left:3px;vertical-align:text-bottom;\" src=\"https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1\"></a></p>"

execute:
  freeze: auto
  warning: false

bibliography: references.bib
csl: american-statistical-association.csl
citations-hover: true
footnotes-hover: true

knitr:
  opts_chunk:
    comment: "##"
    results: "hold"

format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    css: assets/css/styles.css
    code-link: true
    code-fold: false
    code-tools:
      toggle: true
      source: false
    self-contained: true
    toc: true
    toc-location: right
    toc-title: Contents
    highlight-style: arrow
    code-block-background: true
    code-block-border-left: false
    fontsize: 12pt
    code-overflow: scroll
    code-line-numbers: false
